version: '3'

networks:
    laravel:

services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html:delegated
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    php:
        build:
            context: ./docker
            dockerfile: php.Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - laravel
        working_dir: /var/www/html

    node:
        image: node:current-alpine
        volumes:
            - .:/var/www/html
        ports:
            - "3000:3000"
            - "3001:3001"
        working_dir: /var/www/html
        networks:
            - laravel

    queue:
        image: php:8-fpm-alpine
        volumes:
            - .:/var/www/html
        restart: always
        depends_on:
            - php
            - app
        networks:
            - laravel
        command: [ "php", "artisan", "queue:work" ]
